### ISSUE TITLE
Set up the local dev environment

### ISSUE THREAD

**Issue by alan-khosro** [invisement/easy-speak-app#1]
Deliverables:
- []

Description

Tasks

- [ ] 
- [x] - [x] install flutter and dart (latest stable version)
- [x] install android studio (latest stable version)
- [x] clone repo: https://github.com/invisement/easy-speak-app
- [x] commit a hello commit to the repo and PR (pull request) to review and accept
    - I recommend creating a markdown doc for yourself and document many things like to-do, useful commands, suggestions, technical debts to discuss, issues to add to backlog, etc (your personal notebook)

**Comment by carlitos-206** [comment]
I just created a PR awaiting your review to close this issue

**Comment by alan-khosro** [comment]
@andreaa0819 I finished the first task but the second need ...
